import Head from 'next/head'
import { Inter } from '@next/font/google'
import WhatWeDo from '@/components/home/WhatWeDo'
import Footer from '@/components/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WhatWeDo />
        <Footer />
        Welcome
      </main>
    </>
  )
}
